# Default, Defaults
# markdown: redcarpet
# highlighter: pygments
# or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Jekyll Defaults
title: Nui Blog
email: thichthat@gmail.com
description: "Blog cá nhân của Nui"
baseurl: "/blog"
paginate: 5
paginate_path: "/blog/page:num"
keywords: "voge"
# the subpath of your site, e.g. /blog

# Site settings
title:       Nui Blog
email:       thichthat@gmail.com
url: "https://ngxson.github.io"
relative_permalinks: false

sass:
  sass_dir: _sass
  style: :compressed
links:
  facebook: voge.org
  #twitter: brijeshb42
  email: info.voge@gmail.com
  #github: brijeshb42/bitwiser-material/
exclude:
  - bower_components
  - README.md
full_name: Brijesh

author: "Nui Nui"
authorBio: "Trời tính không bằng máy tính"
